(function(){
    'use strict';

    /**
     * This is a sample directive
     * Generated by ng-appgen Yeomen/Angular generator.
     */
    angular.module('common').directive('createitem', function() {

        //TODO: Implement your complex directive logic here
        return {
            restrict: 'E',
            replace: true,
            scope: {

            },
            templateUrl: 'common/directives/createitem.html',
            link: function(scope, element, attrs, fn) {

            }
        };

    });

})();
