(function(){
    'use strict';

    /**
     * This is a sample directive
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('common').directive('myitemList', function() {

        //TODO: Implement your complex directive logic here
        return {
            restrict: 'E',
            replace: true,
            scope: {
                items: '='
            },
            templateUrl: 'common/directives/myitem-list.html',
            link: function(scope, element, attrs, fn) {

            }
        };

    });

})();
