(function(){
    'use strict';

    /**
     * This is a sample directive
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Jose Carlos Fernandez
     */
    angular.module('common').directive('searchbox', function($location) {
        
        //TODO: Implement your complex directive logic here
        return {
            restrict: 'E',
            replace: true,
            scope: {

            },
            templateUrl: 'common/directives/searchbox.html',
            link: function($scope, element, attrs, fn) {
                $scope.search = function() {
                    var searchText = $scope.text;
                    $scope.text = "";
                    $location.url('/results/').search({text: searchText});
                };
            }
        };

    });

})();
