(function(){
    'use strict';

    /**
     * This is a sample module
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('home', ['ui.bootstrap', 'ui.utils', 'ngRoute', 'ngAnimate', 'restangular']);
    
    angular.module('home').config(function($routeProvider) {

        $routeProvider.when('/home', {
            templateUrl: 'home/templates/home-template.html',
            controller: 'homeController'
        });
        /* Add New Routes Above */

    });
    

})();
