(function(){
    'use strict';

    /**
     * This is the main application file.
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('frontendTest', ['ui.bootstrap', 'ui.utils', 'ngRoute', 'ngAnimate', 'restangular', 'angular-loading-bar', 'home', 'common', 'results', 'backendMock']);
    
    angular.module('frontendTest').config(function($routeProvider) {

        /* Add New Routes Above */
        $routeProvider.otherwise({redirectTo:'/home'});

    });
    
    angular.module('frontendTest').run(function($rootScope) {

        $rootScope.safeApply = function(fn) {
            var phase = $rootScope.$$phase;
            if (phase === '$apply' || phase === '$digest') {
                if (fn && (typeof(fn) === 'function')) {
                    fn();
                }
            } else {
                this.$apply(fn);
            }
        };

    });

})();
