(function(){
    'use strict';

    /**
     * This is a sample filter spec
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    describe('capitalize', function() {

        var filter;

        beforeEach(function() {
            module('common');

            inject(function($filter) {
                filter = $filter('capitalize');
            });
        });

        it('should ...', function() {

            //TODO: Implement your filter spec logic here
            //expect(filter('input')).toEqual('output');

        });

    });

})();
