(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Jose Carlos Fernandez
     */
    angular.module('home').service('homeService', function($http, $q) {

        var message = '';

        this.getMessage = function(){
            if(message === ''){
                message = 'Congratulations! Your app is fully up and running.';
            }

            return message;
        };

    });

})();
